apiVersion: v1
kind: Service
metadata:
  name: nodeserverload
spec:
  selector:
    app: nodeserver
  type: NodePort
  ports:
  - name: nodeserver-service
    port: 8080
    targetPort: 3000
    protocol: TCP